from typing import TypeVarTuple

D = TypeVarTuple("D")


class Aggregate[*D]:
    """Marker class to indicate a Domain is an aggregate of multiple domains.

    The build method will be automatically generated by the Domain metaclass
    when a Domain is defined as Domain[Aggregate[Domain1, Domain2, ...]].
    """

    pass
