"""User service implementing business logic for user operations."""

from datetime import datetime
from typing import Optional

from domain.models import User
from domain.repositories.user_repository import UserRepository
from application.dtos.user_dtos import UserCreate, UserUpdate, UserView, UserListView


class UserService:
    """
    User service encapsulating user-related business logic.
    
    This service demonstrates:
    - Dependency on repository interface (not implementation)
    - Business logic and validation
    - DTO conversion
    """
    
    def __init__(self, user_repository: UserRepository) -> None:
        """
        Initialize service with repository dependency.
        
        Args:
            user_repository: User repository interface
        """
        self.user_repository = user_repository
    
    def create_user(self, user_create: UserCreate) -> UserView:
        """
        Create a new user.
        
        Args:
            user_create: User creation DTO
            
        Returns:
            Created user view
            
        Raises:
            ValueError: If username already exists
        """
        # Business logic: Check username uniqueness
        existing = self.user_repository.get_by_username(user_create.username)
        if existing:
            raise ValueError(f"Username '{user_create.username}' already exists")
        
        # Convert DTO to domain model, providing system fields
        user = user_create.to_domain(
            id=0,  # Will be auto-generated by database
            created_at=datetime.utcnow(),
        )
        
        # Persist domain model
        created_user = self.user_repository.create(user)
        
        # Convert to ViewDTO and return
        return UserView.build(created_user)
    
    def get_user(self, user_id: int) -> Optional[UserView]:
        """
        Get user by ID.
        
        Args:
            user_id: User ID
            
        Returns:
            User view or None if not found
        """
        user = self.user_repository.get_by_id(user_id)
        return UserView.build(user) if user else None
    
    def list_users(self, skip: int = 0, limit: int = 100) -> list[UserListView]:
        """
        List all users.
        
        Args:
            skip: Number of records to skip
            limit: Maximum number of records
            
        Returns:
            List of user views
        """
        users = self.user_repository.list_all(skip, limit)
        return [UserListView.build(user) for user in users]
    
    def update_user(self, user_id: int, user_update: UserUpdate) -> UserView:
        """
        Update existing user.
        
        Args:
            user_id: User ID to update
            user_update: Update DTO
            
        Returns:
            Updated user view
            
        Raises:
            ValueError: If user not found or username conflict
        """
        # Get existing user
        user = self.user_repository.get_by_id(user_id)
        if not user:
            raise ValueError(f"User with id {user_id} not found")
        
        # Check username uniqueness if updating username
        if user_update.username and user_update.username != user.username:
            existing = self.user_repository.get_by_username(user_update.username)
            if existing:
                raise ValueError(f"Username '{user_update.username}' already exists")
        
        # Apply updates (only set fields that are provided)
        update_data = user_update.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(user, field, value)
        
        # Persist changes
        updated_user = self.user_repository.update(user)
        
        # Return view
        return UserView.build(updated_user)
    
    def delete_user(self, user_id: int) -> bool:
        """
        Delete user by ID.
        
        Args:
            user_id: User ID to delete
            
        Returns:
            True if deleted, False if not found
        """
        return self.user_repository.delete(user_id)
